### PR TITLE
fix: race condition when mutations were completing/erroring

### PR DESCRIPTION
**Pull request by bennyhobart**
When queries were completing two of the queries with the same serialization key were getting queued, this is because the completion block would run before dequeue, removing the subscription from the queue and calling `startFirstOpIfNotStarted`, dequeue would then be called, removing this subscription and starting another one

### CODE REVIEW

**Comment by bennyhobart** [comment]
ping @helfer

**Comment by helfer** [comment]
Sorry @bennyhobart, I only just saw this. I tried to understand the issue you described, and I also looked at the test, but I couldn't figure it out. Can you open an issue and describe the issue in more detail? Specifically: 1) what are you trying to accomplish? 2) What did you expect to happen? 3) What happened instead?

Thanks!

**Comment by bennyhobart** [comment]
Hey @helfer ,
Suppose this link is passed 3 operations, with matching `serializationKey`'s
A = Inflight
B, C = Queued
A will continue, B and C will be held in memory until A
When A Resolved it's `onCompletion` handler would fire first, removing this operation from the `opQueue` and Starting the next operation
A = Complete
B = Inflight
C = Queued
After the `onCompletion` block is fired `deque` is then called, removing the inflight operation from the `opQueue` and starting the next one
A = Complete
B, C = Inflight
This lead to mutations not serializing correctly as C could resolve before B

Hopefully that clarifies, it's a subtle bug

**Comment by helfer** [comment]
Thanks for the PR @bennyhobart ! It had a few extraneous commits in there, so I went ahead and fixed it myself. Published fix in v2.1.0.

**Pull request closed without merging**
