### PR TITLE
Feature/apollo client v3

### PR DESCRIPTION
**Pull request by kgrowinski**
What was done:
 * Update imports to reflect @apollo/client v3 paths
 * Update typing in some places
 * Prettifying files
 * Change TsLint to ESLint
 * Added Prettier for better code formation
 * Added simplified ESLint rules

Why it was needed:
 * ApolloClient released new version with breaking changes
 * TSLint is deprecated since 2019

Side Effects:
 * Not all rules from `tslint.json`(old) are reflected in `.eslintrc.json`(new)

### CODE REVIEW

**Review by James-Firth — COMMENTED** [review]
@krzysztofgrowinski I noticed this PR adds a `package-lock.json` to the project, did you install with `npm` instead of `yarn` at some point?

I could see that being a sticking point since the rest of the project seems to use `yarn`.

**Comment by krzysztofgrowinski** [comment]
@James-Firth there is package-lock.json on master branch I used both bpm and yarn to update dependencies versions in both package-lock.json and yarn.lock

**Comment by James-Firth** [comment]
@krzysztofgrowinski I'm sorry you're right, I must have misread when I gave it a skim. Thanks for the PR!

**Review by helfer — CHANGES_REQUESTED** [review]
Hey @krzysztofgrowinski, thanks a lot for your PR!
It would be a lot easier for me to review this PR if it didn't include formatting changes. Currently, this PR changes pretty much every line. It would be easiest for me to review if each change (Apollo Client 3.0, tslint -> eslint) was split into a separate PR, and didn't include formatting changes from prettier (I'd prefer just running that myself). Please let me know if you want to split this PR. If not, I will probably just do the upgrade myself.

**Comment by krzysztofgrowinski** [comment]
Sure I can do that. 
One thing without these ESlint changes pipelines will fail. Is that ok?

**Comment by krzysztofgrowinski** [comment]
@helfer I opened separate [PR](https://github.com/helfer/apollo-link-serialize/pull/24) feel free to close this one if it wont be needed anymore. I skipped changing TSLint config to ESLint because of lack of time.

**Comment by helfer** [comment]
I merged your other PR, but as you said there were a bunch of linter errors. I didn't have time to look into all of them, so I'll try merging this one instead.

**Comment by helfer** [comment]
Just published these changes as 4.0 on npm. 🎉 Thanks a lot @krzysztofgrowinski!

**Pull request merged**
